staleLabel: stale

exemptLabels:
  - bug

issues:
  limitPerRun: 1
  daysUntilStale: 1
  daysUntilClose: 2
  markComment: >
    This issue has been automatically marked as stale because it has not had activity in the
    last 1 day. It will be closed tomorrow unless it is tagged "bug".
  closeComment: >
    This issue has been automatically closed because it has not had activity in the
    last 2 days.