# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Open Targets
author: Open Targets Team
email: contact@opentargets.org
description: > # this means to ignore newlines until "baseurl:"
  Open Targets is a public-private initiative to generate evidence on the validity of therapeutic targets based on genome-scale experiments and analysis.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: targetvalidate
github_username:  opentargets
linkedin: https://www.linkedin.com/company/centre-for-therapeutic-target-validation
facebook: https://www.facebook.com/OpenTargets/
repository: opentargets/opentargets.github.io

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

#minima allows to specify the order in the header:
header_pages:
  - overview.md
  - projects.md
  - people.md
  - jobs.md
  - contact.md
