# Set Jekyll environment to "production" to ensure that 
# Google Analytics code is added to <head> section on each page
# see _includes/ga.html and _includes/head.html

[context.production]
  [context.production.environment]
    JEKYLL_ENV = "production"


[context.deploy-preview]
  APP_ENV = "deploy-preview"